name: DynalinksExample
options:
  bundleIdPrefix: com.dynalinks
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"

packages:
  DynalinksSDK:
    path: ..

targets:
  DynalinksExample:
    type: application
    platform: iOS
    sources:
      - DynalinksExample
    dependencies:
      - package: DynalinksSDK
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.dynalinks.example
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"
        GENERATE_INFOPLIST_FILE: YES
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
